domains:
- domain: dev.surveychimp-groupseven.me
  type: PRIMARY
name: surveychimp-test
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  envs:
  - key: MONGO_DATABASE_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:G4xpCCILpclEbQfa4rt10riX7HWydJn1:RwSdaFBwec8M9JJ7jduZ7x74Wod4ejH1p++UUVeHnUJLNlcS0mPzafJyYWJ0oIzGBKcgH8bBCPrjB4QX8Z4g/UtdtqT6R4HsqVAQoMMjf/RhKVuyNVAZVBowrrBMbO4jivzNfE0mZ8Ls0Wlkh5fIFXwUHtGGhosdhD4DnPdVsFUnbgd25hiMt/YaI+xEbCW2AGmWYwytCcZgTCjsSHp5Ig==]
  github:
    branch: dev
    deploy_on_push: true
    repo: LindaMarko/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp
  routes:
  - path: /api
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /
static_sites:
- build_command: npx nx run surveychimp-survey-spa:build:production
  catchall_document: index.html
  environment_slug: node-js
  envs:
  - key: NX_ENABLE_FOUR_STAR_FEATURE
    scope: BUILD_TIME
    value: "true"
  github:
    branch: dev
    deploy_on_push: true
    repo: LindaMarko/surveychimp
  name: surveychimp2
  output_dir: dist/apps/surveychimp-survey-spa
  routes:
  - path: /
  source_dir: /