domains:
- domain: prod.surveychimp-groupseven.me
  type: PRIMARY
name: surveychimp-prod
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  envs:
  - key: MONGO_DATABASE_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:nQLEniDNhQ4BrhNuCuXUS65fNrjcc7jn:hCCkpy0iuzQq7iMKa+/LMMOR2jDxT85o2AqhA05tTxxMCaE70gNJhDQ33TdHv94r7U5B0/JCxs594T90Y+4Hgse8pCSBYfSV8i+YRCxrP8K0GWQNgYCKJRcwocJV5tqEyRjL69Uv0hkd1nVT3Lu3pD6OChnEvp2ih2gD83IZio3er/4fUo/6DQrUY4G3KAhPenbKhQkmVDg+v3GuN5OrZA==]
  github:
    branch: main
    deploy_on_push: true
    repo: LindaMarko/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp
  routes:
  - path: /api
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /
static_sites:
- build_command: npx nx run surveychimp-survey-spa:build:production
  environment_slug: node-js
  github:
    branch: main
    repo: LindaMarko/surveychimp
  name: surveychimp2
  output_dir: dist/apps/surveychimp-survey-spa
  routes:
  - path: /
  source_dir: /