@baseUrl=https://dev.surveychimp-groupseven.me/api


POST {{baseUrl}}/survey
Content-Type: application/json

{
    "recipient": {
        "name": "Linda",
        "mobileNumber": "070 123 12 12"
    }
}

###

GET {{baseUrl}}/survey/63611db618be8f1da687f314


###

PATCH {{baseUrl}}/survey/635ad5b2cf3d50daaa87c966
Content-Type: application/json

{
    "rating": 3,
    "comment": "Det var toppen!"
}